import{a as f,S as p,i as c}from"./assets/vendor-RTzsIgW4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&t(m)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const y=f.create({baseURL:"https://pixabay.com/api/",params:{key:"55362008-0a0d101fe7347dac3fa7e75ec",safesearch:!0}}),h=async(e,a)=>(await y.get("",{params:{q:e,image_type:"photo",orientation:"horizontal",per_page:"15",page:a}})).data,i={searchForm:document.querySelector(".form"),loadMoreBtn:document.querySelector(".js-loadMoreBtn"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader")},L=new p(".gallery a"),w=e=>{const a=e.map(t=>`<li class="galleryItem">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
          <ul class="informationList">
            <li class="informationItem">Likes <span class="infoAmount">${t.likes}</span></li>
            <li class="informationItem">Views <span class="infoAmount">${t.views}</span></li>
            <li class="informationItem">Comments <span class="infoAmount">${t.comments}</span></li>
            <li class="informationItem">Downloads <span class="infoAmount">${t.downloads}</span></li>
          </ul>
        </a>
      </li>`).join("");return i.galleryList.insertAdjacentHTML("beforeend",a),L.refresh(),[...i.galleryList.querySelectorAll(".galleryItem")].slice(-e.length)},v=async e=>{const a=e.map(s=>s.querySelector("img"));await Promise.all(a.map(s=>new Promise(t=>{s.complete&&t(),s.addEventListener("load",t),s.addEventListener("error",t)})))},q=()=>{i.galleryList.innerHTML=""},I=()=>{i.loader.classList.add("isActive")},u=()=>{i.loader.classList.remove("isActive")},P=()=>{i.loadMoreBtn.classList.add("isActive")},d=()=>{i.loadMoreBtn.classList.remove("isActive")},l={maxWidth:"550px",position:"topRight"},n={page:1,totalPage:1,query:""},S=e=>{n.totalPage=Math.ceil(e/15)},g=async({query:e,page:a})=>{try{d(),I();const s=await h(e,a);if(s.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");S(s.totalHits);const t=await w(s.hits);await v(t),t.forEach(r=>r.classList.add("isActive")),u(),n.page>=n.totalPage||P()}catch(s){u(),c.error({title:"Error",message:s.message,...l})}},b=async e=>{try{e.preventDefault();const a=e.target.elements["search-text"].value.trim();if(a==="")throw new Error("Search query is empty");n.query=a,n.page=1,q(),await g(n)}catch(a){c.error({title:"Error",message:a.message,...l})}},A=async()=>{try{n.page+=1,await g(n);const e=document.querySelector(".galleryItem").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),n.page>=n.totalPage&&(d(),c.info({message:"We're sorry, but you've reached the end of search results.",...l}))}catch(e){d(),c.error({title:"Error",message:e.message,...l})}};i.searchForm.addEventListener("submit",b);i.loadMoreBtn.addEventListener("click",A);
//# sourceMappingURL=index.js.map
