import{a as f,S as p,i as l}from"./assets/vendor-RTzsIgW4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const y=f.create({baseURL:"https://pixabay.com/api/",params:{key:"55362008-0a0d101fe7347dac3fa7e75ec",safesearch:!0}}),h=async(e,a)=>(await y.get("",{params:{q:e,image_type:"photo",orientation:"horizontal",per_page:"15",page:a}})).data,n={searchForm:document.querySelector(".form"),loadMoreBtn:document.querySelector(".js-loadMoreBtn"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader")},L=new p(".gallery a"),w=e=>{const a=e.map(t=>`<li class="galleryItem">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
          <ul class="informationList">
            <li class="informationItem">Likes <span class="infoAmount">${t.likes}</span></li>
            <li class="informationItem">Views <span class="infoAmount">${t.views}</span></li>
            <li class="informationItem">Comments <span class="infoAmount">${t.comments}</span></li>
            <li class="informationItem">Downloads <span class="infoAmount">${t.downloads}</span></li>
          </ul>
        </a>
      </li>`).join("");return n.galleryList.insertAdjacentHTML("beforeend",a),L.refresh(),[...n.galleryList.querySelectorAll(".galleryItem")].slice(-e.length)},v=async e=>{const a=e.map(o=>o.querySelector("img"));await Promise.all(a.map(o=>new Promise(t=>{o.complete&&t(),o.addEventListener("load",t),o.addEventListener("error",t)})))},q=()=>{n.galleryList.innerHTML=""},I=()=>{n.loader.classList.add("isActive")},m=()=>{n.loader.classList.remove("isActive")},S=()=>{n.loadMoreBtn.classList.add("isActive")},u=()=>{n.loadMoreBtn.classList.remove("isActive")},d={maxWidth:"550px",position:"topRight"},i={page:1,totalPage:1,query:""},b=e=>{i.totalPage=Math.ceil(e/15)},g=async({query:e,page:a})=>{try{u(),I();const o=await h(e,a);if(o.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");b(o.totalHits);const t=await w(o.hits);if(await v(t),t.forEach(r=>r.classList.add("isActive")),m(),i.page>=i.totalPage)throw new Error("We`re sorry, but you`ve reached the end of search results.");S()}catch(o){console.dir(o),m(),l.error({title:"Error",message:o.message,...d})}},A=async e=>{try{e.preventDefault();const a=e.target.elements["search-text"].value.trim();if(a==="")throw new Error("Search query is empty");i.query=a,i.page=1,q(),await g(i)}catch(a){l.error({title:"Error",message:a.message,...d})}},E=async()=>{try{i.page+=1,await g(i);const e=document.querySelector(".galleryItem").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(e){u(),l.error({title:"Error",message:e.message,...d})}};n.searchForm.addEventListener("submit",A);n.loadMoreBtn.addEventListener("click",E);
//# sourceMappingURL=index.js.map
